POST  http://localhost:5000/api/booking/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTQ3Y2E4NmZjOTg2MDM4MjdmNGY2ODUiLCJpYXQiOjE3NjYzMTI2MDEsImV4cCI6MTc2NjMxNjIwMX0.PRLG5asm2rwa1dMI1km9lJfpRNU2HVRw87DwO_7Da20
Content-Type: application/json

{
    "flightId": "6947caf7cae760a4832a79aa",
    "passengerName": "sachin chandra"
}


